2018-12-07 08:23:13|ERROR|Invoice_Collect.Go|exception 'PDOException' with message 'Incorrect datetime value: '' for column 'endTime' at row 1' in D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php:258
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php(410): NotORM_Result->query('UPDATE vich_inv...', Array)
#1 D:\wamp\www\jxc\api\PhalApi\PhalApi\Model\NotORM.php(48): NotORM_Result->update(Array)
#2 D:\wamp\www\jxc\api\Version1\Domain\Invoice\CURD.php(124): PhalApi_Model_NotORM->update(65, Array)
#3 D:\wamp\www\jxc\api\Version1\Api\Invoice\Collect.php(50): Domain_Invoice_CURD->collect(Array)
#4 [internal function]: Api_Invoice_Collect->go()
#5 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#6 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#7 {main}
2018-12-07 08:24:47|ERROR|Invoice_Collect.Go|exception 'PDOException' with message 'Incorrect datetime value: '' for column 'endTime' at row 1' in D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php:258
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php(410): NotORM_Result->query('UPDATE vich_inv...', Array)
#1 D:\wamp\www\jxc\api\PhalApi\PhalApi\Model\NotORM.php(48): NotORM_Result->update(Array)
#2 D:\wamp\www\jxc\api\Version1\Domain\Invoice\CURD.php(124): PhalApi_Model_NotORM->update(64, Array)
#3 D:\wamp\www\jxc\api\Version1\Api\Invoice\Collect.php(50): Domain_Invoice_CURD->collect(Array)
#4 [internal function]: Api_Invoice_Collect->go()
#5 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#6 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#7 {main}
2018-12-07 08:44:00|ERROR|Warning_Message.Go|exception 'PDOException' with message 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where to_days(createTime)=to_days(now()))' at line 1' in D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php:258
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php(811): NotORM_Result->query('SELECT * FROM v...', Array)
#1 D:\wamp\www\jxc\api\PhalApi\NotORM\NotORM\Result.php(857): NotORM_Result->execute()
#2 D:\wamp\www\jxc\api\Version1\Model\Message.php(19): NotORM_Result->fetch()
#3 D:\wamp\www\jxc\api\Version1\Domain\Message\Msg.php(87): Model_Message->invoiceMsgExists('41')
#4 D:\wamp\www\jxc\api\Version1\Api\Warning\Message.php(10): Domain_Message_Msg::InvoiceWaning('32')
#5 [internal function]: Api_Warning_Message->go()
#6 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#7 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#8 {main}
2018-12-07 12:55:22|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(64, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-07 13:13:54|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(65, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
2018-12-07 15:18:58|ERROR|Order_Save.Go|exception 'PDOException' with message 'There is no active transaction' in D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php:328
Stack trace:
#0 D:\wamp\www\jxc\api\PhalApi\PhalApi\DB\NotORM.php(328): PDO->rollBack()
#1 D:\wamp\www\jxc\api\Version1\Domain\Order\Save.php(117): PhalApi_DB_NotORM->rollback('db_demo')
#2 D:\wamp\www\jxc\api\Version1\Api\Order\Save.php(24): Domain_Order_Save->save(68, 1, NULL)
#3 [internal function]: Api_Order_Save->go()
#4 D:\wamp\www\jxc\api\PhalApi\PhalApi.php(55): call_user_func(Array)
#5 D:\wamp\www\jxc\api\Public\v1\index.php(14): PhalApi->response()
#6 {main}
